### ISSUE TITLE
QnA

### ISSUE THREAD

**Issue by LEEHYUNDONG** [LEEHYUNDONG/CS_study#1]
## 파트
몇 주차/어느 파트
### 질문 
질문 내용

**Comment by LEEHYUNDONG** [comment]
@guswns3371 
## 파트
01월12일 2주차/hash

### 질문
```java
int m = hashTableSize; // m : 해시 테이블의 크기
int hash = X.hashCode(); // hashCode() : 자바 객체의 hash function 
int index = hash % m; // hash bucket 인덱스
```
현준님, 위 코드에서 두번째 줄에 X는 key 값이죠?? 
그리고 X hashing하는 함수를 사용하셨는데 hashCode()를 쓰면 크기가 int 자료형 기준 가장 긴 int형 정수가 generate 되나요??

**Comment by guswns3371** [comment]
## 답변
X는 자바객체입니다.
hashCode() 메소드 반환값이 int형 입니다. 
hashCode() 관련 내용은 
- https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html
- https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hashCode(java.lang.Object)
에서 확인하시면 될것 같아요!

generate 되는 hashCode()값이 `int 자료형 기준 가장 긴 int형 정수`형으로 정해지진 않는것 같아요. (이 부분은 저도 검색해보고 알려드릴게요)

**Comment by LEEHYUNDONG** [comment]
아아 이해 했습니다. hash(x)처럼 동작하는거라고 생각했는데, 그냥 hashCode()를 쓰면 hash값을 반환해주는군요.
친절한 답변 감사합니다.
👍👍
